# Generated by Django 4.0.2 on 2022-02-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urllist',
            old_name='user_id',
            new_name='user',
        ),
    ]
